(IN-PACKAGE :AAF)
(DEFVAR *REALIZATIONS*
  '(WEAKLY-ADMISSIBLE-EXTENSIONS
    (((NIL (A) (B) (C) (A C) (B C)) (MAKE-AAF '(A B C) '((A B) (B A))))
     ((NIL (A) (B) (A B) (C) (A C) (B C) (A B C))
      (MAKE-AAF '(A B C)
                '((((A B C)) (MAKE-AAF '(A B C) 'NIL))
                  (((A) (B) (C)) (MAKE-AAF '(A B C) '((B A) (B C) (A B) (A C) (C B) (C A))))
                  (((A C) (B C)) (MAKE-AAF '(A B C) '((A B) (B A))))
                  (((A B) (C)) (MAKE-AAF '(A B C) '((B C) (C B) (C A))))
                  (((A B) (A C) (B C))
                   (MAKE-AAF '(A B C Z1 Z2 Z3 Z4)
                             '((Z4 A) (Z4 B) (Z4 C) (Z3 Z4) (A Z3) (B Z1) (Z2 Z4) (Z1 Z4) (C Z2)))))))
     ((NIL (A) (C) (B C)) (MAKE-AAF '(A B C Z1 Z2) '((Z2 Z1) (Z1 B) (B Z2) (A C) (C Z1) (C A))))
     ((NIL (A) (B) (C)) (MAKE-AAF '(A B C) '((B A) (B C) (A B) (A C) (C B) (C A))))
     ((NIL (A) (B) (A B) (C)) (MAKE-AAF '(A B C) '((B C) (A C) (C B) (C A))))
     ((NIL (A) (C) (A C) (B C) (A B C)) (MAKE-AAF '(A B C Z1 Z2) '((Z2 B) (Z2 C) (Z1 Z2) (B Z1) (C Z2))))
     ((NIL (B) (A B) (C) (B C)) (MAKE-AAF '(A B C Z1) '((Z1 B) (Z1 A) (B Z1) (A C) (C Z1) (C A))))
     ((NIL (B) (A B) (B C))
      (MAKE-AAF '(A B C Z1 Z2) '((A Z1) (A C) (Z2 A) (Z2 B) (B Z2) (B Z1) (Z1 Z2) (Z1 B) (Z1 C) (C A))))
     ((NIL (A B) (C)) (MAKE-AAF '(A B C Z1) '((Z1 B) (Z1 A) (B C) (A Z1) (C Z1) (C B) (C A))))
     ((NIL (B) (A B) (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3) '((Z3 B) (A Z2) (B Z3) (B Z1) (C Z2) (Z2 Z3) (Z1 A) (Z1 C))))
     ((NIL (A) (A B) (C) (A C) (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2) '((A Z1) (B Z2) (Z2 Z1) (Z1 A) (Z1 B) (Z1 C) (C Z1))))
     ((NIL (A B) (C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3) '((A Z2) (Z3 A) (Z3 B) (Z3 Z1) (B Z3) (B Z1) (Z2 A) (Z2 Z3) (Z2 B) (Z1 Z2))))
     ((NIL (B) (C) (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4)
                '((A Z3) (Z4 B) (B Z4) (B Z1) (Z3 Z4) (Z3 Z2) (Z2 A) (Z2 C) (C Z2) (Z1 A))))
     ((NIL (A) (A B) (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4)
                '((Z4 B) (Z4 C) (Z3 Z2) (Z3 B) (Z3 C) (Z2 Z1) (Z1 Z3) (Z1 A) (A Z4) (B Z3) (B Z2) (C Z1))))
     ((NIL (A) (B) (A C) (B C))
      (MAKE-AAF '(A B C Z1 Z2) '((Z2 A) (Z2 B) (Z2 C) (A Z2) (A B) (Z1 Z2) (B Z2) (B A) (C Z1))))
     ((NIL (A) (B) (A B) (C) (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3) '((Z3 A) (Z3 B) (Z3 C) (A Z1) (B Z3) (Z2 Z3) (C Z2) (Z1 Z3))))
     ((NIL (A) (A B) (B C))
      (MAKE-AAF '(A B C Z1 Z2)
                '((B Z1) (Z2 B) (Z2 A) (Z2 C) (Z1 B) (Z1 Z2) (Z1 C) (A Z2) (A Z1) (A C) (C Z2) (C A))))
     ((NIL (C) (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4)
                '((A Z1) (C Z2) (B Z4) (B Z3) (Z4 B) (Z3 A) (Z2 C) (Z2 B) (Z1 Z4) (Z1 Z2))))
     ((NIL (A) (A B) (A C) (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4)
                '((Z4 Z1) (Z3 Z2) (Z3 A) (Z2 A) (Z2 C) (A Z1) (B Z4) (B Z2) (C Z3) (Z1 B) (Z1 C))))
     ((NIL (A) (B) (A C) (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4 Z5)
                '((Z5 B) (Z4 A) (Z4 C) (Z3 Z4) (Z3 Z2) (Z3 Z1) (A Z2) (A Z1) (Z2 A) (Z2 C) (Z1 Z4) (Z1 Z2)
                  (Z1 B) (B Z3) (C Z5) (C Z4))))
     ((NIL (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4)
                '((Z4 Z2) (Z3 A) (Z3 B) (Z3 C) (A Z1) (Z2 B) (Z2 C) (B Z4) (B Z3) (Z1 Z3) (C Z2) (C Z1))))
     ((NIL (C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4 Z5)
                '((Z5 Z4) (Z4 B) (Z4 A) (Z4 Z2) (B Z5) (B Z2) (A Z4) (A Z1) (Z3 A) (Z3 C) (Z2 Z5) (Z2 B) (Z2 A)
                  (C Z3) (Z1 Z3))))
     ((NIL (A B) (B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3)
                '((Z3 A) (Z3 B) (Z3 C) (A Z3) (A C) (A Z1) (Z2 A) (Z2 B) (B Z2) (B Z1) (C Z3) (C A) (Z1 Z3)
                  (Z1 Z2) (Z1 B) (Z1 C))))
     ((NIL (A B) (A C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4)
                '((Z4 C) (A Z3) (Z3 A) (Z3 B) (Z3 Z1) (B Z4) (Z2 Z3) (C Z2) (C Z1) (Z1 A) (Z1 B) (Z1 Z2))))
     ((NIL (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4 Z5 Z6)
                '((A Z1) (Z6 Z5) (Z5 B) (Z5 Z2) (B Z6) (Z4 Z2) (Z3 A) (Z3 Z5) (Z2 Z3) (Z2 C) (Z1 Z3) (C Z4))))
     ((NIL (A) (B) (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4 Z5 Z6)
                '((Z6 B) (Z6 C) (Z6 Z1) (Z5 Z6) (Z4 Z3) (Z4 A) (Z3 Z1) (Z2 Z4) (A Z2) (B Z6) (C Z5) (C Z4)
                  (C Z3) (C Z1) (Z1 Z5) (Z1 B) (Z1 C))))
     ((NIL (A) (B) (A B) (C) (A C) (B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4) '((Z4 A) (Z4 B) (Z4 C) (A Z1) (B Z3) (Z3 Z4) (Z2 Z4) (C Z2) (Z1 Z4))))
     ((NIL (A B) (A C) (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3)
                '((A Z2) (A Z1) (Z3 A) (Z3 Z1) (Z3 B) (Z3 C) (Z2 A) (Z2 Z3) (Z2 B) (Z2 C) (Z1 A) (Z1 Z2) (Z1 B)
                  (Z1 C) (B Z3) (B Z1) (C Z3) (C Z2))))
     ((NIL (A) (B) (C) (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4)
                '((A Z3) (Z4 Z1) (Z3 Z2) (Z3 Z1) (B Z1) (Z2 A) (Z2 Z4) (Z2 B) (Z2 C) (C Z4) (C Z2) (Z1 A)
                  (Z1 B) (Z1 Z2) (Z1 C))))
     ((NIL (B) (A B) (C) (A C) (B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4 Z5)
                '((A Z4) (B Z5) (B Z3) (Z5 A) (Z5 B) (Z5 Z3) (Z4 Z2) (Z3 Z2) (C Z5) (C Z1) (Z2 A) (Z2 B) (Z2 C)
                  (Z1 Z2))))
     ((NIL (B) (A B) (A C) (B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4 Z5)
                '((A Z5) (A Z2) (Z5 B) (Z5 C) (Z4 Z5) (Z4 Z3) (Z4 B) (Z3 A) (Z3 B) (Z3 C) (B Z5) (B Z1) (Z2 Z3)
                  (Z2 Z1) (Z1 A) (Z1 Z3) (Z1 C) (C Z4))))
     ((NIL (B) (C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4 Z5)
                '((B Z3) (B Z2) (Z5 Z4) (Z5 Z2) (Z5 Z1) (A Z1) (Z4 Z5) (Z4 A) (Z4 C) (Z4 Z3) (C Z5) (C Z4)
                  (Z3 Z1) (Z2 B) (Z2 A) (Z2 C) (Z2 Z3) (Z1 B) (Z1 A) (Z1 Z4) (Z1 C) (Z1 Z2)))))
    WEAKLY-PREFERRED-EXTENSIONS
    ((((A B) (B C)) (MAKE-AAF '(A B C) '((A C) (C A)))) (((A B C)) (MAKE-AAF '(A B C) 'NIL))
     (((A B) (C)) (MAKE-AAF '(A B C) '((C B) (C A) (B C))))
     (((A) (B) (C)) (MAKE-AAF '(A B C) '((B A) (B C) (A B) (A C) (C B) (C A))))
     (((A B) (A C) (B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4) '((A Z3) (Z4 Z1) (B Z4) (C Z2) (Z3 Z1) (Z2 Z1) (Z1 A) (Z1 B) (Z1 C)))))
    UNDISPUTED-EXTENSIONS
    ((((A B) (B C)) (MAKE-AAF '(A B C) '((A C) (C A)))) (((A B C)) (MAKE-AAF '(A B C) 'NIL))
     (((B C) (A B C)) (MAKE-AAF '(A B C Z1) '((Z1 Z1) (Z1 A))))
     (((A) (A B) (A C) (A B C)) (MAKE-AAF '(A B C Z1) '((Z1 B) (Z1 Z1) (Z1 C))))
     (((A B) (C)) (MAKE-AAF '(A B C) '((A C) (C B) (C A))))
     (((A) (A B) (C) (B C)) (MAKE-AAF '(A B C Z1) '((A C) (C A) (Z1 B) (Z1 Z1))))
     (((A) (B) (C)) (MAKE-AAF '(A B C) '((B A) (B C) (A B) (A C) (C B) (C A))))
     (((B) (A B) (B C)) (MAKE-AAF '(A B C Z1) '((Z1 Z1) (Z1 C) (C A))))
     ((NIL (A) (B) (A B) (C) (B C)) (MAKE-AAF '(A B C Z1) '((Z1 B) (Z1 Z1) (Z1 C) (C A))))
     ((NIL (A) (B) (A B) (C)) (MAKE-AAF '(A B C Z1) '((Z1 Z1) (Z1 C) (C B) (C A))))
     ((NIL (A) (A B) (C)) (MAKE-AAF '(A B C Z1) '((B C) (C A) (Z1 B) (Z1 Z1))))
     ((NIL (A) (B) (C)) (MAKE-AAF '(A B C Z1 Z2) '((B Z1) (A B) (A C) (Z2 A) (Z2 Z2) (C Z2) (Z1 A) (Z1 Z1))))
     (((A) (C) (B C)) (MAKE-AAF '(A B C Z1) '((Z1 Z1) (Z1 B) (A B) (A C) (C A))))
     ((NIL (A) (B) (A C) (B C))
      (MAKE-AAF '(A B C Z1 Z2) '((Z2 Z2) (Z2 C) (A B) (B A) (C Z1) (Z1 A) (Z1 B) (Z1 Z1))))
     ((NIL (B) (C) (A C) (B C)) (MAKE-AAF '(A B C Z1 Z2) '((A Z1) (Z2 Z2) (Z2 B) (B A) (Z1 Z1) (Z1 C))))
     (((C) (B C) (A B C)) (MAKE-AAF '(A B C Z1 Z2) '((Z2 Z2) (Z2 A) (A Z1) (Z1 B) (Z1 Z2))))
     (((A) (A B) (B C)) (MAKE-AAF '(A B C Z1) '((A C) (C A) (C Z1) (Z1 B) (Z1 Z1))))
     (((A) (B) (C) (B C)) (MAKE-AAF '(A B C Z1) '((B A) (A B) (A C) (C A) (Z1 B) (Z1 C) (Z1 Z1))))
     ((NIL (A B) (C)) (MAKE-AAF '(A B C Z1 Z2) '((B C) (A Z2) (C B) (C A) (Z2 C) (Z2 Z2) (Z1 B) (Z1 Z1))))
     (((C) (A B C)) (MAKE-AAF '(A B C Z1 Z2 Z3) '((Z3 Z1) (Z2 Z2) (Z2 B) (B Z1) (Z1 B) (Z1 A) (A Z3))))
     ((NIL (A) (B) (A B) (A C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3) '((Z3 Z3) (Z3 Z2) (Z2 B) (Z2 C) (Z1 A) (Z1 Z2) (C Z1))))
     ((NIL (C) (A C) (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3) '((Z3 Z3) (Z3 A) (Z3 B) (Z2 A) (Z2 C) (A Z2) (A Z1) (B Z2) (Z1 Z3))))
     ((NIL (A) (B) (A B) (C) (A C) (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2) '((Z2 Z2) (Z2 A) (Z2 B) (Z1 C) (Z1 Z1))))
     ((NIL (C) (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3) '((B Z2) (Z3 Z3) (Z3 A) (A Z1) (Z2 C) (Z2 Z1) (Z1 B))))
     ((NIL (C) (A C) (B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4)
                '((A B) (A Z1) (Z4 A) (Z4 C) (B Z2) (C Z4) (Z3 A) (Z3 Z3) (Z2 C) (Z2 Z2) (Z1 Z4) (Z1 Z3))))
     ((NIL (B) (C) (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3) '((Z3 B) (Z3 C) (B Z2) (Z2 Z3) (A Z3) (Z1 A) (Z1 Z1))))
     ((NIL (A C) (B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3) '((A Z3) (Z3 A) (Z3 B) (Z3 C) (Z2 Z2) (Z2 B) (B A) (B Z3) (C Z1) (Z1 Z3))))
     ((NIL (A) (B) (A B) (C) (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3) '((Z3 Z3) (Z3 A) (Z3 C) (Z2 Z3) (Z2 B) (A Z1) (C Z2) (Z1 B) (Z1 Z1))))
     ((NIL (A) (A C) (B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3) '((A B) (B A) (B Z3) (C Z1) (Z3 C) (Z3 Z3) (Z2 B) (Z2 Z2) (Z1 A) (Z1 Z2))))
     ((NIL (C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3) '((B Z2) (Z3 Z3) (Z3 A) (Z2 C) (Z2 Z1) (A Z1) (Z1 B) (Z1 A))))
     ((NIL (A B) (C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3) '((Z3 Z3) (Z3 B) (Z3 C) (A Z1) (B Z2) (Z2 A) (Z2 B) (Z1 Z2))))
     ((NIL (A C) (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3) '((Z3 Z1) (A Z1) (Z2 A) (Z2 Z2) (Z2 B) (Z1 A) (Z1 B) (Z1 C) (B Z1) (C Z3))))
     ((NIL (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3) '((Z3 Z2) (A Z3) (Z2 A) (Z2 B) (Z2 C) (Z1 Z1) (Z1 B) (B Z2) (C Z3))))
     ((NIL (A) (B) (A B) (C) (A C) (B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4) '((Z4 Z1) (Z3 Z1) (A Z4) (B Z3) (Z2 Z1) (Z1 A) (Z1 B) (Z1 C) (C Z2))))
     ((NIL (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3) '((Z3 Z1) (B Z3) (Z2 Z2) (Z2 A) (Z2 C) (Z1 B) (Z1 A) (Z1 C) (A Z3) (C Z1))))
     ((NIL (B) (C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4)
                '((Z4 Z3) (B Z4) (Z3 B) (Z3 A) (Z3 C) (A Z3) (Z2 Z3) (Z1 A) (Z1 Z1) (C Z2))))
     ((NIL (B) (A B) (A C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4 Z5 Z6 Z7 Z8)
                '((Z8 Z8) (Z8 C) (A Z7) (Z7 Z6) (Z6 A) (Z6 Z5) (Z6 Z2) (Z5 Z4) (Z5 Z1) (B Z2) (B Z1) (Z4 B)
                  (Z4 Z3) (Z3 Z5) (Z2 Z6) (Z2 Z3) (C Z6) (Z1 B) (Z1 C))))
     ((NIL (A) (B) (A C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4 Z5)
                '((A Z3) (Z5 Z4) (Z5 Z1) (Z4 B) (B Z5) (Z3 Z1) (Z2 Z4) (Z2 Z2) (Z2 C) (C Z1) (Z1 A) (Z1 C))))
     ((NIL (A) (B) (A B) (A C) (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3)
                '((Z3 A) (Z3 B) (Z3 C) (A Z3) (B Z3) (Z2 Z3) (Z2 Z1) (C Z2) (Z1 A) (Z1 B) (Z1 C) (Z1 Z1))))
     ((NIL (A) (B) (C) (A C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4 Z5 Z6 Z7)
                '((Z7 Z6) (Z7 Z5) (Z7 Z4) (Z6 Z2) (Z5 Z2) (Z4 Z2) (Z3 Z2) (Z3 C) (A Z1) (Z2 Z7) (Z2 Z3) (Z2 A)
                  (Z2 B) (B Z4) (B Z3) (Z1 Z6) (Z1 B) (Z1 C) (C Z5))))
     ((NIL (A) (A B) (C) (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4 Z5)
                '((A Z5) (Z5 B) (Z5 C) (Z4 A) (Z4 B) (Z3 Z3) (Z3 C) (B Z2) (Z2 Z4) (Z2 Z1) (Z1 A) (Z1 Z1)
                  (C Z4))))
     ((NIL (A) (B) (C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4 Z5)
                '((Z5 Z5) (Z5 A) (Z5 B) (Z4 Z2) (Z4 Z1) (Z3 Z3) (Z3 Z1) (A Z3) (A Z2) (B Z1) (C Z4) (Z2 A)
                  (Z2 C) (Z1 B) (Z1 C) (Z1 Z2))))
     ((NIL (B) (A B) (A C) (B C) (A B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4 Z5 Z6)
                '((Z6 A) (Z6 C) (Z5 A) (Z5 B) (Z5 C) (A Z6) (A Z3) (B Z6) (B Z5) (Z4 B) (Z4 C) (C Z5) (C Z1)
                  (Z3 Z5) (Z3 Z2) (Z2 A) (Z2 Z4) (Z2 Z2) (Z1 Z4))))
     ((NIL (A) (B) (A B) (A C) (B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4)
                '((Z4 B) (Z4 Z2) (Z4 C) (Z3 A) (Z3 Z2) (A Z4) (B Z3) (Z2 A) (Z2 B) (Z2 C) (Z1 Z3) (Z1 Z2)
                  (C Z1)))))
    STRONGLY-UNDISPUTED-EXTENSIONS
    ((((A B C)) (MAKE-AAF '(A B C) 'NIL))
     (((A) (B) (C)) (MAKE-AAF '(A B C) '((B A) (B C) (A B) (A C) (C B) (C A))))
     (((A C) (B C)) (MAKE-AAF '(A B C) '((A B) (B A)))) (((A B) (C)) (MAKE-AAF '(A B C) '((B C) (C B) (C A))))
     (((A B) (A C) (B C))
      (MAKE-AAF '(A B C Z1 Z2 Z3 Z4) '((Z4 A) (Z4 B) (Z4 C) (Z3 Z4) (A Z3) (B Z1) (Z2 Z4) (Z1 Z4) (C Z2)))))))